repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
        stages: [commit, push]
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.58.1
    hooks:
      - id: golangci-lint
        additional_dependencies: []
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.9.0
    hooks:
      - id: eslint
        name: eslint (frontend)
        args: ["--max-warnings=0"]
        files: ^frontend/.*\.(ts|tsx|js|jsx)$
        additional_dependencies: []
