version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: tridot-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ../../ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../../ops/prometheus/rules:/etc/prometheus/rules:ro
      - ../../ops/prometheus/targets:/etc/prometheus/targets:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-admin-api"
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: tridot-alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ../../ops/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.9.6
    container_name: tridot-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ../../ops/loki/config.yml:/etc/loki/config.yml:ro
      - loki-data:/loki
    command:
      - "-config.file=/etc/loki/config.yml"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:10.3.1
    container_name: tridot-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    volumes:
      - ../../ops/grafana/provisioning:/etc/grafana/provisioning:ro
      - ../../ops/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - monitoring
    depends_on:
      - prometheus
      - loki

networks:
  monitoring:
    name: tridot-monitoring

volumes:
  loki-data:
