---
- name: Install WireGuard packages
  ansible.builtin.package:
    name:
      - wireguard
      - wireguard-tools
      - iptables
    state: present

- name: Deploy WireGuard config
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: "0600"
  notify:
    - Restart wireguard

- name: Enable and start WireGuard interface
  ansible.builtin.systemd:
    name: wg-quick@wg0.service
    enabled: true
    state: started
