apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus-default
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: GET
      prometheusType: Prometheus
      timeInterval: 30s
    editable: true

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: loki-default
    url: http://loki:3100
    editable: true
