name: agent-ci

on:
  push:
    paths:
      - "node-agent/**"
      - ".github/workflows/ci-agent.yaml"
  pull_request:
    paths:
      - "node-agent/**"
      - ".github/workflows/ci-agent.yaml"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Go fmt check
        run: test -z "$(gofmt -l .)"
        working-directory: node-agent
      - name: Go test
        run: go test ./...
        working-directory: node-agent
