name: backend-ci

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/ci-backend.yaml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/ci-backend.yaml"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install tools
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Go fmt check
        run: test -z "$(gofmt -l .)"
        working-directory: backend
      - name: Go test
        run: go test ./...
        working-directory: backend
      - name: Gosec
        run: gosec ./...
        working-directory: backend
