name: frontend-ci

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/ci-frontend.yaml"
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/ci-frontend.yaml"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
        working-directory: frontend
      - name: Lint
        run: pnpm lint
        working-directory: frontend
      - name: Test
        run: pnpm test -- --watch=false
        working-directory: frontend
